names:
  0: 大方块
  1: 橡胶玩具球
  2: 小丑鱼摆件
  3: 黑色乌龟玩具
  4: 红色小球
  5: 粉色奶瓶玩具
  6: 绿色六边形玩具
  7: 粉色小河豚玩具
  8: 深绿色积木块
  9: 小企鹅摆件
  10: 女弓箭手摆件
  11: 小砖块玩具
  12: 奇妙萌可徽章
  13: 白色小球
  14: 拼图模块
  15: 纽扣
  16: 黑色颗粒小糖果
  17: 玩具珠
  18: 袋装小糖果（未拆封）
  19: 橡胶圈
  20: 小乐高
  21: 玩具零件
  22: 玻璃珠
  23: 餐巾纸
  24: 干燥剂
  25: 鸭子玩具
  26: 螺丝
  27: 贴纸
  28: 游戏币
  29: 面签头
  30: 微颗粒
  16: 线条
